package String;

/*

Description:
    -> This program calculates the minimum time required to make a rope colorful...
    -> The rope consists of balloons, each having a color represented by a character in a string...
    -> Removing a balloon takes a specific amount of time, given in the times array...
    -> The goal is to ensure that no two adjacent balloons have the same color while minimizing the total removal time...

Problem Statement:
    You are given a string colors and an integer array times of the same length...
    Each character in colors represents the color of a balloon, and each element in times represents
    the time needed to remove that balloon...
    Remove some balloons so that no two adjacent balloons have the same color, 
    while minimizing the total removal time...

Example:
    Input:
        colors = "abaac"...
        times = [1, 2, 3, 4, 5]...
    Output:
        3...
    Explanation:
        Remove the balloon at index 2 (color 'a', time = 3)...
        After removal, no two adjacent balloons have the same color...

Approach:
    1. Iterate through the string from the second character onwards...
    2. Compare each character with its previous one...
    3. If two adjacent balloons have the same color:
        - Add the smaller removal time to the total sum...
        - Update the current balloon's time to the larger of the two times
          (keeping the costlier one for future comparisons)...
    4. Continue until the end of the string...
    5. Return the accumulated sum as the minimum total removal time...

Key Observations:
    -> Only adjacent balloons with the same color cause a conflict...
    -> Keeping the balloon with the higher removal time helps minimize total cost...
    -> Updating the times array in place ensures efficient handling of consecutive duplicates...

Time and Space Complexity:
    -> Time Complexity: O(n)...
       (Each balloon is processed once)...
    -> Space Complexity: O(1)...
       (No extra space used except variables)...

Example Walkthrough:
    Input:
        colors = "abbc"...
        times = [1, 2, 3, 4]...
    Process:
        Step 1: Compare 'a' and 'b' → different, no action...
        Step 2: Compare 'b' and 'b' → same, add min(2,3)=2, keep max(2,3)=3...
        Step 3: Compare 'b' and 'c' → different, no action...
    Output:
        Minimum removal time = 2...

*/

public class Minimum_Time_To_Make_Rope_Colorful {

    private static int minCost(String colors, int[] times) {

        int sum = 0;
        int n = colors.length();
        for (int i = 1; i < n; i++) {

            char curr = colors.charAt(i);
            char prev = colors.charAt(i - 1);

            if (curr == prev) {
                sum += Math.min(times[i], times[i - 1]);
                times[i] = Math.max(times[i], times[i - 1]);
            }
        }
        return sum;
    }

    public static void main(String[] args) {

        String colors = "abaac";
        int[] times = {1, 2, 3, 4, 5};

        System.out.println("The minimum time to make the rope colorful is : " + minCost(colors, times));

    }

}
