package Math_Problems;

/*

Description:
    -> This program generates a specific row of Pascal’s Triangle using an iterative approach...
    -> Pascal’s Triangle is a triangular array where each element is the sum of the two elements directly above it in the previous row...
    -> The first and last elements of each row are always 1...

Problem Statement:
    You are given an integer `rowIndex`...
    You need to return the `rowIndex`th (0-indexed) row of Pascal’s Triangle...

Example:
    Input:
        rowIndex = 3...
    Output:
        The row is : 1 3 3 1...

Explanation:
    Pascal’s Triangle looks like this:
        Row 0 → [1]...
        Row 1 → [1, 1]...
        Row 2 → [1, 2, 1]...
        Row 3 → [1, 3, 3, 1]...
    Thus, the 3rd row is [1, 3, 3, 1]...

Approach:
    1. Initialize a list `ansList` with the first row containing only 1...
    2. For each iteration up to `rowIndex`, build the next row from the previous one...
    3. Create a temporary list `tempList` starting with 1...
    4. For each element in the previous row (except the first and last), calculate the sum of two adjacent elements and add it to the temporary list...
    5. End each row with another 1 to complete the triangle property...
    6. Assign `tempList` to `ansList` for the next iteration...
    7. After completing all iterations, `ansList` will represent the desired row of Pascal’s Triangle...

Key Observations:
    -> The triangle is symmetric, and each value is derived from the sum of the two numbers above it...
    -> The first and last elements of each row are always 1...
    -> Each iteration depends only on the previous row, allowing efficient computation...

Time and Space Complexity:
    -> Time Complexity: O(rowIndex²) since each row up to `rowIndex` is computed iteratively...
    -> Space Complexity: O(rowIndex), as only the current and previous rows are stored at any given time...

Example Walkthrough:
    Input: rowIndex = 3...
    Process:
        - Row 0 → [1]...
        - Row 1 → [1, 1]...
        - Row 2 → [1, 2, 1]...
        - Row 3 → [1, 3, 3, 1]...
    Output:
        The row is : 1 3 3 1...

*/

import java.util.ArrayList;

public class Pascals_Triangle_II {

    private static ArrayList<Integer> getRow(int rowIndex) {
        ArrayList<Integer> ansList = new ArrayList<>();
        ansList.add(1);

        for (int i = 0; i < rowIndex; i++) {
            ArrayList<Integer> tempList = new ArrayList<>();

            tempList.add(1);
            for (int j = 1; j < ansList.size(); j++) {
                tempList.add(ansList.get(j - 1) + ansList.get(j));
            }
            tempList.add(1);

            ansList = tempList;
        }

        return ansList;

    }

    public static void main(String[] args) {

        int rowIndex = 3;
        ArrayList<Integer> row = getRow(rowIndex);

        System.out.print("The row is : ");
        for (int num : row) {
            System.out.print(num + " ");
        }
        System.out.println();

    }
    
}
